ExpenseManager/Models/ErrorViewModel.cs
using System;

namespace ExpenseManager.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ExpenseManager/Models/FundRecord.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Models
{
    public class FundRecord
    {
        public int Id { get; set; }

        public int FundAmount { get; set; }
        public int MainFundId { get; set; }
        public int SubFundId { get; set; }
        public string SubFund { get; set; }

        public DateTime CreateAt { get; set; }

        public DateTime? UpdateAt { get; set; }
        public string UpdatedAtString
        {
            get
            {
                if (UpdateAt != null)
                {
                    return UpdateAt.Value.ToString("yyyy/MM/dd hh:mm:ss tt");
                }
                else
                    return "";
            }
        }
    }
}

ExpenseManager/Models/Funds.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Models
{
    public class Funds
    {
        public int Id { get; set; }
        [Required]
        public string FundName { get; set; }
        
    }
}

ExpenseManager/Models/SubFunds.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Models
{
    public class SubFunds
    {
        public int Id { get; set; }

        public string SubFund { get; set; }
        
        public int MainFundId { get; set; }
    }
}

ExpenseManager/Controllers/FundController.cs
using ExpenseManager.DAL;
using ExpenseManager.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Controllers
{
    public class FundController : Controller
    {
        private readonly IFunds _Fund;
        private readonly ISubFunds _SubFunds;

        public FundController(IFunds Fund, ISubFunds SubFunds)
        {
            _Fund = Fund;
            _SubFunds = SubFunds;
        }

        public IActionResult Index()
        {
            return View(_Fund.FundList());
        }

        public IActionResult CreateFund()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SaveFund(Funds Fund)
        {
            _Fund.InsertFund(Fund);
            return RedirectToAction("Index");
        }


        public IActionResult CreateSubFund()
        {
            return View(_Fund.FundList());
        }


        public void SaveSubFund(SubFunds subFunds)
        {
            _SubFunds.SaveSubFunds(subFunds);
        }

        public IActionResult GetSubFundById(int id) {
            var data = _SubFunds.GetSubFundById(id);
            return Json(data);
        }

        public IActionResult ViewMainFund()
        {
            var data = _Fund.FundList();
            return View(data);
        }

        public IActionResult ViewSubFund()
        {
            var data = _SubFunds.SubFundList();
            return View(data);
        }

        public IActionResult EditMainFund(int id)
        {
            var data =_Fund.GetMainFundById(id);
            return View(data);
        }

        [HttpPost]
        public IActionResult UpdateMainFund(Funds fund)
        {
            _Fund.UpdateMainFund(fund);
            return RedirectToAction("ViewMainFund");
        }

        public IActionResult DeleteMainFund(int id) {
            _Fund.DeleteMainFundById(id);
            return RedirectToAction("ViewMainFund");
        }

        public IActionResult EditSubFund(int id)
        {
            var data = _SubFunds.GetSubFund(id);
            return View(data);
        }

        [HttpPost]
        public IActionResult UpdateSubFund(SubFunds fund)
        {
            _SubFunds.UpdateSubFund(fund);
            return RedirectToAction("ViewSubFund");
        }

        public IActionResult DeleteSubFund(int id)
        {
            _SubFunds.DeleteSubFundById(id);
            return RedirectToAction("ViewSubFund");
        }


    }
}

ExpenseManager/Controllers/FundRecordController.cs
using ExpenseManager.DAL;
using ExpenseManager.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Controllers
{
    public class FundRecordController : Controller
    {
        private readonly IFundRecord _funds;

        private readonly IFunds mainFund;
        private readonly ISubFunds subFund;

        public FundRecordController(IFundRecord funds, IFunds mainFund, ISubFunds subFund)
        {
            _funds = funds;
            this.mainFund = mainFund;
            this.subFund = subFund;
        }

        public IActionResult GetFundRecordById(FundRecord fund)
        {
            List<FundRecord> data = _funds.GetFundRecordById(fund);
            return Json(data);
        }
        public IActionResult Index(FundRecord fund)
        {
            List<Funds> mainFundList = mainFund.FundList();
            ViewBag.mainFundList = mainFundList;
            return View();
        }

        //[HttpGet]
        //public IActionResult ViewFundRecord(FundRecord fund)
        //{
            
        //}

        [HttpPost]
        public IActionResult CreateFundRecord(FundRecord fundRecord)
        {
            _funds.InsertFundRecord(fundRecord);
            return Json(new { result = "redirect", url = Url.Action("Index", "Fund") });
        }

        public IActionResult GetSubFundById(int id)
        {
            List<SubFunds> subFundList = subFund.GetSubFundById(id);
            return Json(subFundList);
        }

        public IActionResult GetParticularFundRecordById(int id)
        {
            var data = _funds.GetParticularFundRecordById(id);
            return Json(data);
        }

        [HttpPost]
        public IActionResult UpdateFundRecord(FundRecord fundRecord)
        {
            var data = _funds.UpdateFundRecord(fundRecord);
            return Json(data);
        }

        public IActionResult DeleteFundRecord(int id)
        {
            _funds.DeleteFundRecord(id);
            return Json("success");
        }
    }
}

ExpenseManager/Controllers/HomeController.cs
using ExpenseManager.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ExpenseManager.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ExpenseManager/Views/Fund/CreateFund.cshtml
@{
    ViewData["Title"] = "Funds";
}

@model Funds
<div class="row">
    <div class="col-md-8">
        <form asp-action="SaveFund" asp-controller="Fund" method="post">
            <div class="form-group">
                <label asp-for="FundName">Fund Name</label>
                <input type="text" class="form-control" placeholder="Enter fund name" asp-for="FundName"/>
                <span asp-validation-for="FundName"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create Fund" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

ExpenseManager/Views/Fund/CreateSubFund.cshtml
@{
    ViewData["Title"] = "";
}

@model List<Funds>
<div class="row">
    <div class="col-md-12">
        <select class="custom-select addSubFund" aria-label="Default select example" id="MainFundId">
            <option selected value="">Create sub fund</option>
            @foreach (var item in Model)
            {
                <option value="@item.Id">@item.FundName</option>
            }
        </select>
    </div>
    <div class="col-md-12 subFund d-none">
    </div>
</div>

@section Scripts{ 
<script>
    $(document).ready(function () {
        $(".addSubFund").change(function () {
            if ($('.addSubFund').val() == '') {
                $(".subFund").hide();
            } else {
                $(".subFund").show();
                $(".subFund").empty();
                var data = "";
                data += "<div class='form-group mt-3'>";
                data += "<label>Sub Fund</label>";
                data += "<input type='text' class='form-control' id='subFund' name='SubFund' />";
                data += "<button class='btn btn-success mt-2' id='createSubFund'> Create Sub Fund </button>";
                data += "</div>";
                $(".subFund").append(data).removeClass("d-none");
            }
        });
       
        $("body").on('click', '#createSubFund', function () {
            var mainFundId = $(".addSubFund").val();
            $.ajax({
                url: "/Fund/SaveSubFund",
                data: { "SubFund": $('#subFund').val(), "MainFundId": $('#MainFundId').val() },
                type: "GET",
                success: function () {
                    window.location.replace("Index");
                },
                error: function () { }
            });
        });
    });
</script>
}

ExpenseManager/Views/Fund/EditMainFund.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model Funds
<div class="row">
    <div class="col-md-8">
        <form asp-action="UpdateMainFund" method="post">
            <div class="form-group">
                <label class="control-label">Main Fund</label>
                <input class="form-control" asp-for="@Model.FundName" />
                <input type="hidden" asp-for="@Model.Id" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Update</button>
            </div>
            
        </form>
    </div>
</div>

ExpenseManager/Views/Fund/EditSubFund.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@model SubFunds
<div class="row">
    <div class="col-md-8">
        <form asp-action="UpdateSubFund" method="post">
            <div class="form-group">
                <label class="control-label">Main Fund</label>
                <input class="form-control" asp-for="@Model.SubFund" />
                <input type="hidden" asp-for="@Model.Id" />
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-success">Update</button>
            </div>

        </form>
    </div>
</div>

ExpenseManager/Views/Fund/Index.cshtml
@{ 
    ViewData["Title"] = "Funds";
}

@model List<Funds>
<a class="btn btn-success mb-3" asp-action="Index" asp-controller="FundRecord">Create New Fund</a>
<div class="row">
    <div class="col-md-6">
        <select class="custom-select" id="mainFundId" aria-label="Default select example">
            <option selected value="">Select main fund</option>
            @foreach (var item in Model)
            {
                <option value="@item.Id">@item.FundName</option>
            }
        </select>
    </div>
    <select class="custom-select subFund d-none col-md-6" id="subFundId">       
    </select>
</div>
<div class="row fundRecord d-none mt-4">
    <table class="table table-striped table-bordered">
        <thead>
            <tr>
                <th>#</th>
                <th>Fund Name</th>
                <th>Last Updated</th>
                <th>Fund Ammount</th>
                <th></th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>

@section Scripts{ 
<script>
    $(document).ready(function () {
        
        $("body").on('change', '#mainFundId', function () {
            var MainFundId = $("#mainFundId").val();
            if (MainFundId == '') {
                $(".subFund").addClass('d-none');
            }
            if (MainFundId != '') {
                $.ajax({
                    url: "/Fund/GetSubFundById?id=" + MainFundId,
                    type: "GET",
                    data: { "id": $("#mainFundId").val()},
                    success: function (response) {
                        let html = '';
                        html += "<option selected value=''>Select sub fund</option>"; 
                        $.each(response, function (key, item) {
                            html += "<option value=" + item.id + ">" + item.subFund;
                            html += "</option>";
                        });
                        html += "</select>";
                        $(".subFund").removeClass("d-none").html(html);
                    },
                    error: function () {},
                });
            }
        });
        var MainFundId = "";
        var SubFundId = ""
        $("body").on("change", "#subFundId", function () {
            MainFundId = $("#mainFundId").val();
            SubFundId = $("#subFundId").val();
            if (SubFundId != '') {
                myFunction();
            }  
        });

        function myFunction() {
            $.ajax({
                url: "/FundRecord/GetFundRecordById",
                type: "GET",
                data: { MainFundId: MainFundId, SubFundId: SubFundId },
                success: function (response) {
                    var html = '';
                    $.each(response, function (key, item) {
                        html += '<tr>';
                        html += '<td>' + (key + 1) + '</td>';
                        html += '<td>' + item.subFund + '</td>';
                        html += '<td>' + item.updatedAtString + '</td>';
                        html += '<td><span class="fundAmmount' + item.id + '">' + item.fundAmount + '</span><span class="fundAmmountSpan fund' + item.id + '"></span></td>';
                        html += "<td><button class='btn btn-primary btn-sm updateFund updateBtn" + item.id + "' name='" + item.id + "'>Edit</button>";
                        html += " <button class='btn btn-sm btn-danger deleteBtn' name='" + item.id + "'>Delete</button>";
                        html += "</td > ";
                        html += '</tr>';
                    });
                    $('.fundRecord').removeClass('d-none');
                    $('tbody').html(html);
                },
                failure: function () { },
            });
        }

        $('body').on("click", ".updateFund", function (e) {
            e.preventDefault();
            //myFunction();
            var id = $(this).attr('name');
            $.ajax({
                url: "FundRecord/GetParticularFundRecordById",
                type: "GET",
                data: { id: id },
                success: function (response) {
                    if (id == response.id) {
                        $('.fundAmmount' + response.id).addClass('d-none');
                        $(".fund" + response.id).append("<input type='text' class='form-control newFund' value='" + response.fundAmount + "'>");
                        $('.updateBtn' + response.id).html("Update");
                        $('.updateBtn' + response.id).removeClass("btn-primary").addClass('btn-success fundId');
                    }
                },
                error: function () {}
            });
        });

        $('body').on('click', '.fundId', function () {
            var id = $('.fundId').attr('name');
            var fundAmmountNum = $('.newFund').val();
            $.ajax({
                url: "FundRecord/UpdateFundRecord",
                type: "post",
                data: { Id: id, FundAmount: fundAmmountNum },
                success: function (response) {
                    myFunction();
                },
                error: function () {}
            });
        });

        $("body").on('click', '.deleteBtn', function () {
            var id = $(this).attr('name');
            if (confirm("Are you sure want to delete fund record.")) {
                $.ajax({
                    url: "FundRecord/DeleteFundRecord",
                    type: "get",
                    data: { id: id },
                    success: function (response) {
                        myFunction();
                    },
                    error: function () { }
                });
            } else {
                return false;
            }
        });
    });
</script>
}
 

ExpenseManager/Views/Fund/ViewMainFund.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<a asp-action="CreateFund" asp-controller="Fund" class="btn btn-success mb-3">Create Main Fund</a>

@model List<Funds>

<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Fund Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model.Count > 0)
            {
                int i = 0;
                foreach (var item in Model)
                {
                    <tr>
                        <td>@(i + 1)</td>
                        <td>@item.FundName</td>
                        <td>
                            <a class="btn btn-primary btn-sm" asp-action="EditMainFund" asp-route-Id="@item.Id" asp-controller="Fund">Edit</a>
                            <a class="btn btn-danger btn-sm" asp-action="DeleteMainFund" asp-route-Id="@item.Id" asp-controller="Fund" onclick="return confirm('Are you sure want to delete this fund?')">Delete</a>
                        </td>
                    </tr>
                    i++;
                }
            }
            else
            {
                <tr>
                    <td colspan="3">No data available</td>
                </tr>
            }
        }

    </tbody>
</table>

ExpenseManager/Views/Fund/ViewSubFund.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<a asp-controller="Fund" asp-action="CreateSubFund" class="btn btn-success mb-3">Create Sub Fund</a>
@model List<SubFunds>

<table class="table table-striped">
    <thead>
        <tr>
            <th>#</th>
            <th>Fund Name</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @{
            if (Model.Count > 0)
            {
                int i = 0;
                foreach (var item in Model)
                {
                    <tr>
                        <td>@(i + 1)</td>
                        <td>@item.SubFund</td>
                        <td>
                            <a class="btn btn-primary btn-sm" asp-action="EditSubFund" asp-route-Id="@item.Id" asp-controller="Fund">Edit</a>
                            <a class="btn btn-danger btn-sm" asp-action="DeleteSubFund" asp-route-Id="@item.Id" asp-controller="Fund" onclick="return confirm('Are you sure want to delete this fund?')">Delete</a>
                        </td>
                    </tr>
                    i++;
                }
            }
            else
            {
                <tr>
                    <td colspan="3">No data available</td>
                </tr>
            }
        }

    </tbody>
</table>

ExpenseManager/Views/FundRecord/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "New Fund Record";
}

@model FundRecord
<h1>Save New Fund</h1>
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label for="inputState">Main Fund</label>
                <select id="mainFundId" class="form-control" asp-for="MainFundId">
                    <option selected>Choose main fund</option>
                    @foreach (var item in ViewBag.mainFundList)
                    {
                        <option value="@item.Id">@item.FundName</option>
                    }
                </select>
            </div>
        </div>
        <div class="col-md-8">
            <div class="form-group">
                <label for="inputState">Sub Fund</label>
                <select id="subFundId" class="form-control subFund" asp-for="SubFundId">
                    <option selected value="">Choose sub fund</option>
                </select>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-8">
            <div class="form-group">
                <label class="inputState">Amount</label>
                <input type="number" asp-for="FundAmount" id="fundAmount" class="form-control" placeholder="Enter ammount" />
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <button class="btn btn-success btn-md" id="createFundRecord">Save Fund</button>
            </div>
        </div>
    </div>

@section Scripts{
    <script>
    $(document).ready(function () {

        $("body").on('change', '#mainFundId', function () {
            var MainFundId = $("#mainFundId").val();
            //if (MainFundId == '') {
            //    $(".subFund").addClass('d-none');
            //}

            if (MainFundId != '') {
                $.ajax({
                    url: "GetSubFundById?id=" + MainFundId,
                    type: "GET",
                    data: { "id": $("#mainFundId").val()},
                    success: function (response) {
                        
                        let html = '';
                        html += "<option selected value=''>Select sub fund</option>";
                        $.each(response, function (key, item) {
                            html += "<option value=" + item.id + ">" + item.subFund;
                            html += "</option>";
                        });
                        
                        $(".subFund").html(html);
                    },
                    error: function () {},
                });
            }
        });

        $("#createFundRecord").click(function () {
            var mainFundId = $("#mainFundId").val();
            var subFundId = $("#subFundId").val();
            var fundAmount = $("#fundAmount").val();
            if (mainFundId == '' || subFundId == '') {
                alert("Please select main and sub fund before proceding.")
                return false;
            }else if (fundAmount == '') {
                alert("Please enter fund amount.");
                return false;
            }
            var newUrl = '@Url.Action("Index", "FundRecord")';
            $.ajax({
                url: "CreateFundRecord",
                type: "POST",
                data: { MainFundId: mainFundId, SubFundId: subFundId, FundAmount: fundAmount },
                success: function (response) {
                    if (response.result == 'redirect') {
                        window.location = response.url;
                    }
                    
                },
                error: function(response){}
            });
        });
    });
    </script>
}

ExpenseManager/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

ExpenseManager/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ExpenseManager</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Fund" asp-action="Index">ExpenseManager</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fund" asp-action="Index">Fund</a>
                        </li>
                        <li>
                            <div class="dropdown">
                                <button class="btn dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Manage Fund
                                </button>
                                <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                    <a asp-action="ViewMainFund" asp-controller="Fund" class="dropdown-item">Manage Main Fund</a>
                                    <a asp-action="ViewSubFund" asp-controller="Fund" class="dropdown-item">Manage Sub Fund</a>
                                </div>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>

    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - ExpenseManager - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>